spring:
  application:
    name: demo-limiter-mq-consumer
  redis:
    port: 6379
    timeout: 2000 # 连接或读取超时时长（毫秒）
    database: 7
    jedis:
      pool:
        max-active: 8
        max-wait: 800
        max-idle: 8
        min-idle: 2
    host: 192.168.56.1
logging:
  level:
    com:
      jdktomcat:
        demo:
          limiter:
            consumer: info

rocketmq:
  name-server: 172.31.184.43:9876
  # When set rocketmq.pull-consumer.group and rocketmq.pull-consumer.topic, rocketmqTemplate will start lite pull consumer
  # If you do not want to use lite pull consumer, please do not set rocketmq.pull-consumer.group and rocketmq.pull-consumer.topic
  pull-consumer:
    group: timmy-consumer-group
    topic: timmy-topic

  # properties used in application code
demo:
  rocketmq:
    topic: timmy-topic
    tlsEnable: false
server:
  port: 0
