dubbo:
  application:
    name: demo-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 10000
    retries: 0
    delay: -1