spring:
  application:
    name: demo-limiter-mq-producer
  redis:
    host: 192.168.56.1
    port: 6379
    timeout: 2000 # 连接或读取超时时长（毫秒）
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 800
        max-idle: 8
        min-idle: 2
rocketmq:
  name-server: 172.31.184.43:9876
  producer:
    group: timmy-group
    sendMessageTimeout: 300000

# properties used in the application
demo:
  rocketmq:
    topic: timmy-topic