spring:
  application:
    name: demo-log-rocketmq

rocketmq:
  namesrvAddr: localhost:9876
  producer:
    groupName: tradeNoProducerGroup
    instanceName: tradeNoProducer
    maxMessageSize: 131072
    sendMsgTimeout: 10000
  consumer:
    groupName: tradeNoConsumerGroup
    instanceName: tradeNoConsumer
    consumeThreadMin: 20
    consumeThreadMax: 64
    batchMaxSize: 1

demo:
  rocketmq:
    topic: string-topic
    topic.user: user-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    bytesRequestTopic: bytesRequestTopic:tagA
    stringRequestTopic: stringRequestTopic:tagA
    objectRequestTopic: objectRequestTopic:tagA
    genericRequestTopic: genericRequestTopic:tagA
    extNameServer: 127.0.0.1:9876
    ext:
      useTLS: false
    producer:
      tls-enable: false

logging:
  level:
    jdktomcat.demo.log.rocketmq.rabbit.RabbitAdvice: info