spring:
  application:
    name: demo-redis-redisson-lock
  data:
    redis:
      password: guess_guess_101
      timeout: 2000
      cluster:
        nodes: 192.168.56.1:7001,192.168.56.1:7002,192.168.56.1:7003,192.168.56.1:7004,192.168.56.1:7005,192.168.56.1:7006
      jedis:
        pool:
          max-active: 8
          max-wait: 800
          max-idle: 8
          min-idle: 2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3307/typayv2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
server:
  port: 0
  address: 192.168.56.202