server:
  port: 0

spring:
  application:
    name: demo-limiter-mq-consumer
  redis:
    host: 192.168.56.1
    port: 6379
    database: 0
    # 过期事件订阅，接收7号数据库中所有key的过期事件
    listen-pattern: __keyevent@0__:expired
    jedis:
      pool:
        max-active: 8
        max-wait: 800
        max-idle: 8
        min-idle: 2
logging:
  level:
    com:
      jdktomcat:
        demo:
          delay: info