server:
  port: 7001

spring:
  application:
    name: demo-skywalking-gateway-route

logging:
  level:
    root: info
  config: classpath:logback.xml
  file:
    name: /data/logs/demo/skywalking/gateway/service/service.log