server:
  port: 7001

spring:
  application:
    name: demo-skywalking-gateway-route

logging:
  level:
    root: info
  config: classpath:logback.xml


sync:
  flag: true
  lease: 5
  rules:
    - path: /orders/ordersfastthirdpartywidthdrew/list
      condition: $request.mostPriorityMatchStatus
      permits: 5
    - path: /orders/ordersfastthirdpartywidthdrew/total
      condition: $request.mostPriorityMatchStatus
      permits: 5
    - path: /orders/ordersfastthirdpartydeposit/total
      permits: 5
    - path: /orders/ordersfastthirdpartydeposit/list
      permits: 5