spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.56.1:3307/typayv2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 1234
debug: true