spring:
  application:
    name: demo-limiter-mq-producer

rocketmq:
  name-server: 172.31.184.45:9876
  producer:
    group: timmy-group
    sendMessageTimeout: 300000

# properties used in the application
demo:
  rocketmq:
    topic: telegram_send_topic:telegram_send_nomal_tag