spring:
  application:
    name: demo-limiter-mq-producer

rocketmq:
  name-server: 172.31.184.45:9876
  producer:
    sendMessageTimeout: 300000
    instanceName: tradeNoProducer
    maxMessageSize: 131072
    namespace: timmy-group

# properties used in the application
demo:
  rocketmq:
    topic: telegram_send_topic:telegram_send_normal_tag